version: "3"
services:
  auth:
    build: ./auth-api
  users:
    build: ./users-api
    environment:
      AUTH_ADDRESS: auth
      AUTH_SERVICE_SERVICE_HOST: auth
    ports: 
      - "8080:8080"
  books:
    build: ./books-api
    ports: 
      - "8000:8000"
    environment:
      AUTH_ADDRESS: auth
    
